# Configurations
title:            CST Part II Bioinformatics
longtitle:        CST Part II Bioinformatics
author:           Kamile Stankeviciute
email:            ks830@cam.ac.uk
description: >
  Computer Science Tripos Part II Bioinformatics notes.

url:              'https://kamilest.github.io'
baseurl:          '/cst-ii-bioinformatics'

remote_theme: pmarsceill/just-the-docs
markdown: kramdown